### PR TITLE
FIX Update "Create new job" button to use bootstrap and escape HTML in messages in GridField

### PR DESCRIPTION
**Pull request by robbieaverill**
Before:

image

After:

image

### CODE REVIEW

**Comment by robbieaverill** [comment]
Tests are fixed in #139

**Comment by nyeholt** [comment]
A quick question on convention here... to better support SS3 => SS4 migrations, I had been thinking that a simpler approach was to define

```
SilverStripe\Core\Injector\Injector:
  QueuedJobService:
    class: \Symbiote\QueuedJobs\Services\QueuedJobService
    # etc
```

That would mean existing `singleton('QueuedJobService')` calls would continue to work. Alternatively something that re-registers the namespaced label into the injector at the 'short' name would work, but feels a little cumbersome. Thoughts? 

(Though that discussion doesn't block this as it stands)

**Comment by robbieaverill** [comment]
@nyeholt yeah I'd wondered whether you wanted to keep injector aliases for various things. I personally don't think you need it for services like this, but it might be useful for user definitions of config in the advanced workflow module for example. Up to you :)

**Comment by nyeholt** [comment]
I actually prefer the alias style of doing things, as otherwise your configuration is binding to a specific namespace wherever you reference that object, which is counter to one of the goals of using a DI. Probably a broader topic to be raised on the dev mailing list

**Comment by robbieaverill** [comment]
For some context- the way this is generally done in SS4 core is that injector services are bound to an interface name, which is then configured in YAML to a specific class (and can be adjusted without breaking APIs, because you expect an interface instance).

That said, in some cases it doesn't really seem necessary to add an interface just to return a single class.

**Comment by sminnee** [comment]
> I actually prefer the alias style of doing things, as otherwise your configuration is binding to a specific namespace wherever you reference that object, which is counter to one of the goals of using a DI. Probably a broader topic to be raised on the dev mailing list

In core code we've tried to take the approach of binding to the FQCN of a relevant interface. It still has a namespace but it's a namespace related to the problem domain rather than the implementation.

Ingo and I had arguments about aliases vs FQCNs at the time:

 * Ingo advocated aliases for brevity's sake (particularly when hand-writing in YML)
 * I advocated FQCNs because otherwise cross-module namespace collisions would still be a risk, which is the whole point of namespaces, and you'd end up with 2 names for everything, which doesn't seem less confusing.

I won the argument at the time.

Like you say, probably something for the dev list, but would be keen to get your views.

**Comment by sminnee** [comment]
> A quick question on convention here... to better support SS3 => SS4 migrations, I had been thinking that a simpler approach was to define

If you create a file calle `.upgrade.yml` in the module with this text:

```
mappings:
  QueuedJobService: Symbiote\QueuedJobs\Services\QueuedJobService
```

Then it should be taken care of for you? It performs exact-match replacements of "QueuedJobService" string literals too, so the singleton calls will be sorted out.

The alias approach might introduce weird edge-case bugs since if code expected to grab the same service in 2 different places but actually had different service instances.

**Pull request merged**
