### PR TITLE
NEW Allow ProcessManager log path to be configurable

### LINKED ISSUE #177: DoormanRunner suppresses ProcessManager errors
Currently cannot set the log path for the ProcessManager:
https://github.com/symbiote/silverstripe-queuedjobs/blob/master/src/Tasks/Engines/DoormanRunner.php#L53

The result is that errors thrown when exec runs the ProcessJobQueueChildTask go to /dev/null.

Preferably the log path can be set for the ProcessManager instance per project, perhaps a hook with the instance passed as an argument is the easiest option.

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves #177

### CODE REVIEW

**Comment by tractorcow** [comment]
I think we should be using a PSR-3 logger, allowing this to be injected to doorman instead of a separate config string.

**Comment by frankmullenger** [comment]
@tractorcow would that require a change to ProcessJobQueueChildTask and/or Doorman ProcessManager? 

At a minimum it will be useful for us to have the standard output and error streams sent somewhere useful:
https://github.com/asyncphp/doorman/blob/master/src/Manager/ProcessManager.php#L132

The problem being that it defaults to /dev/null:
https://github.com/asyncphp/doorman/blob/master/src/Manager/ProcessManager.php#L422

**Comment by tractorcow** [comment]
ok, so it's just the bash shell logging, not something done at the PHP level.

I guess we could do this separately.

**Comment by tractorcow** [comment]
@robbieaverill things that may referenced fixed paths (e.g. `/usr/var/log/doorman.log`) should probably be env-var, not config. Can you add support for an `SS_DOORMAN_LOGPATH` ?

platfrom-specific config is a bit harder, hence my concern. :)

**Comment by frankmullenger** [comment]
Ah right, good point. Yes an environment variable would be preferred thanks.

**Comment by robbieaverill** [comment]
Fair call! Updating

**Pull request merged**
