### PR TITLE
SS41 Fixes

### PR DESCRIPTION
**Pull request by gordonbanderson**
hi

A couple of minor fixes re SS4.1 that I ran into today

Cheers

Gordon

### CODE REVIEW

**Comment by robbieaverill** [comment]
Would you mind switching this to the branch for the version you're using? The stable SS4 release line is 4.0 and 4.1 at the moment

**Comment by dhensby** [comment]
yep, can we target 4.0, please?

**Comment by gordonbanderson** [comment]
I just got bitten by this again... should I create a PR against 4.0 as above or 4.2 which appears to be the current version?

**Comment by robbieaverill** [comment]
@gordonbanderson can you please change the target branch of this pull request (Edit button, top right [don't create a new PR]) to `4.0` and rebase your branch onto that?

We'll get it merged in then merge the branches up

**Comment by dhensby** [comment]
ok, so there's a bug to fix in 4.0 and 4.1 in here so we need to split it into two PRs

**Comment by gordonbanderson** [comment]
I noticed 4.1 was refactored from 4.0, apologies not had time to look into this

**Comment by dhensby** [comment]
no problem @gordonbanderson :)

**Pull request merged**
