### PR TITLE
FIX: Clear the binary field

### PR DESCRIPTION
**Pull request by frankmullenger**
So that PHP is not used to interpret the sake bash script.

### CODE REVIEW

**Comment by tractorcow** [comment]
The task is run as `"{$binary} {$worker}"`, and since sake is ment to be run as a stand-alone process (not under php) this makes sense to me.

Without this prevent `"php vendor/bin/sake"` being incorrectly run.

@robbieaverill do you want to double check my thinking?

**Comment by robbieaverill** [comment]
I don't have any context about this part of the code, but have just skim read the ProcessManager class and can say that:

* the binary property can be a string or null
* if it's null (would be before this PR changed it) it defaults to `$this->binary = PHP_BINDIR . "/php";`
* setting it to an empty string would prevent php from be used to interpret it
* it seems like a sneaky use of the API

Provided it does what the comment says I'm happy =)

**Comment by robbieaverill** [comment]
@frankmullenger do you want to target a specific minor version branch so it'll become a patch release?

**Comment by robbieaverill** [comment]
Oh, d'oh! This was caused by my commit at https://github.com/silverstripe-terraformers/silverstripe-queuedjobs/commit/35fa3c382dca145a2104fcb2f25a50c10f107373#diff-255a2898e87bc13a20569c932b00f920 🤦‍♂️ 

Previously: uses a PHP script
Now: uses a bash script

Options:

* merge this
* switch from using `vendor/bin/sake` to `vendor/silverstripe/framework/cli-script.php`

**Comment by frankmullenger** [comment]
@robbieaverill ah, I see. Probably using the cli-script directly would be better/cleaner in this case. Do you want us to make those changes to this PR?

**Comment by robbieaverill** [comment]
It might be a better option overall, eh? If you agree then yeah that'd be cool =)

**Comment by tractorcow** [comment]
I think going back to the older behaviour is going to be safer in the long run;

**Comment by robbieaverill** [comment]
@frankmullenger last check, are you happy with this going into master or do you want to target one of the minor release branches instead?

**Comment by frankmullenger** [comment]
@robbieaverill happy with master thanks.

**Pull request merged**
